version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 19
    labels:
      - "Type: dependencies"
    groups:
      maven-patch-dependencies:
        update-types:
          - "patch"
      maven-minor-dependencies:
        update-types:
          - "minor"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Type: dependencies"
