-- Create admin user (password: admin)
INSERT INTO ACT_ID_USER (ID_, REV_, FIRST_, LAST_, EMAIL_, PWD_, PICTURE_ID_)
VALUES ('admin', 1, 'Admin', '', null, '{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc=', null);

-- Create admin group
INSERT INTO ACT_ID_GROUP (ID_, REV_, NAME_, TYPE_)
VALUES ('camunda-admin', 1, 'Camunda BPM Administrators', 'SYSTEM');

-- Add admin user to admin group
INSERT into ACT_ID_MEMBERSHIP (USER_ID_, GROUP_ID_)
VALUES ('admin', 'camunda-admin');

-- Add authorizations
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A1', 1, 1, null, 'admin', 1, 'admin', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A2', 1, 1, 'camunda-admin', null, 0, '*', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A3', 1, 1, 'camunda-admin', null, 1, '*', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A4', 1, 1, 'camunda-admin', null, 2, '*', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A5', 1, 1, 'camunda-admin', null, 3, '*', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A6', 1, 1, 'camunda-admin', null, 4, '*', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A7', 1, 1, 'camunda-admin', null, 5, '*', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A8', 1, 1, 'camunda-admin', null, 6, '*', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A9', 1, 1, 'camunda-admin', null, 7, '*', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A10', 1, 1, 'camunda-admin', null, 8, '*', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A11', 1, 1, 'camunda-admin', null, 9, '*', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A12', 1, 1, 'camunda-admin', null, 10, '*', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A13', 1, 1, 'camunda-admin', null, 11, '*', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A14', 1, 1, 'camunda-admin', null, 12, '*', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A15', 1, 1, 'camunda-admin', null, 13, '*', 2147483647);
INSERT INTO ACT_RU_AUTHORIZATION (ID_, REV_, TYPE_, GROUP_ID_, USER_ID_, RESOURCE_TYPE_, RESOURCE_ID_, PERMS_)
VALUES ('A16', 1, 1, 'camunda-admin', null, 14, '*', 2147483647);

