= Taskpool Collector

== Rationale

Taskpool collector is a component usually deployed as a part of the process application
(aside with Camunda BPM Engine) that is responsible for collecting Spring events fired by
the `camunda-eventing-engine-plugin` and creating the corresponding commands for the taskpool.
In doing so, it collects and enriches data and transmits it to taskpool core.

In the following description, we use the term _event_ and _command_. Event denotes a data entity
received from Camunda BPM Engine (from delegate event listener or from history event listener)
which is passed over to the task collector using internal Spring eventing mechanism. The task collector
converts the series of such events into an Taskpool Engine Command - an entity carrying an intent
of change inside of the taskpool core.

== Features

- Collection of task events and history events
- Creation of corresponding task engine commands
- Enrichment of task engine commands with process variables
- Attachment of correlation information to task engine commands
- Transmission of task engine commands
- Provision of properties for process application

== Architecture

[ditaa]
----

 +---------+      +-------------+     +---------+     +--------------+     +-----------+
 |         |      |             |     |         |     |    Task      |     |           |
 | Camunda +-=--->+    Event    +-=---|  Task   +-=-->+   Command    +---->+  Command  |
 |  Event  |      |  Collector  |     | Command |     |   Enricher   |     |   Sender  |
 |     {d} |      |             |     |     {d} |     |   Service    |     |           |
 +---------+      +-------------+     +---------+     +--+-------+---+     +-----------+
                                                         :       ^
                                                         |       :
                                                         V       |
                                                      +--+-------+--+
                                                      |             |
                                                      |   Enricher  |
                                                      |             |
                                                      +-------------+

----

The Taskpool Collector consists of several components:

- Event collector receives Spring Events from `camunda-eventing-engine-plugin` and forms commands
- Enricher performs the command enrichment with payload and data correlation
- Comman sender is responsible for accumulating commands and sending them to command gateway


== Usage and configuration

In order to enable collector component, include the Maven dependency to your process application:

[source,xml]
----
<dependency>
  <groupId>io.holunda.taskpool<groupId>
  <artifactId>camunda-bpm-taskpool-collector</artifactId>
  <version>${camunda-taskpool.version}</version>
<dependency>
----

Then activate the taskpool collector by providing the annotation on any Spring Configuration:

[source,java]
----

@Configuration
@EnableTaskCollector
class TaskCollectorConfigriation {

}

----

=== Event collection

Taskpool collector registers Spring Event Listener to the following events, fired by Camunda Eventing Engine Plugin:

* `DelegateTask` events:
** create
** assign
** delete
** complete
* `HistoryEvent`events:
** HistoricTaskInstanceEvent
** HistoricIdentityLinkLogEvent


=== Task commands enrichment

Alongside with data attributes received from the Camunda BPM engine, the task engine commands
can be enriched with additional business data. There are three enrichment modes available controlled
by the `camunda.taskpool.collector.enricher.type` property:

* `no`: No enrichment takes place
* `process-variables`: Enrichment with process variables
* `custom`: user provides the implementation

==== Process variable enrichment

In particular cases, the task related data is not sufficient for the information required in task list or
other user-related components. The information may be available as process variables and need to be attached
to the task in the taskpool. This is where process variable task enricher can be used. For this purpose,
set the property `camunda.taskpool.collector.enricher.type` to `process-variables` and the enricher will
put all process variables into the task payload (defaults to a empty `EXCLUDE` filter).

You can control what variables will be put into task command payload by providing the Process Variables Filter.
The `ProcessVariablesFilter` is a Spring bean holding a list individual `ProcessVariableFilter` - one per
process definition key.

A `ProcessVariableFilter` can be of the following type:

* `INCLUDE`: task-level include filter, denoting a list of variables to be added for task.
* `EXCLUDE`: task-level exclude filter, denoting a list of variables to be ignored. All other variables are included.
* `PROCESS_INCLUDE`: process-level include filter, denoting a list of variables to be added for all tasks.
* `PROCESS_EXCLUDE`: process-level exclude filter, denoting a list of variables to be ignored for all tasks.

TIP: If you want to implement a custom enrichment, please provide your own implementation of the interface `VariablesEnricher`
(register a Spring Component of the type) and set the property `camunda.taskpool.collector.enricher.type` to `custom`.

=== Data correlation

Apart from task payload attached by the enricher, the so-called correlation with data entries can
be configured. The idea is to attach one or several references (that is `entryType` and `entryId`) to
business data entry(ies) to a task. In a view projection this correlations can be resolved and the
information from business events can be shown together with task information.

The correlation to data events can be configured by providing a `ProcessVariablesCorrelator`. Here is
an example how this can be done:

[source, java]
----
@Bean
open fun processVariablesCorrelator() = ProcessVariablesCorrelator(

  ProcessVariableCorrelation(ProcessApproveRequest.KEY, <1>
    mapOf(
      ProcessApproveRequest.Elements.APPROVE_REQUEST to mapOf( <2>
        ProcessApproveRequest.Variables.REQUEST_ID to BusinessDataEntry.REQUEST
      )
    ),
    mapOf(ProcessApproveRequest.Variables.REQUEST_ID to BusinessDataEntry.REQUEST) <3>
  )
)
----
<1> define correlation for every process
<2> define a correlation for every task needed
<3> define a correlation globally (for the whole process)

The process variable correlator holds a list of process variable correlations - one for every process
definition key. Every `ProcessVariableCorrelation` configures global (that is for every task) or task correlation
(for particular task definition key) by providing a correlation map. A correlation map is keyed by the
process variable name and holds business data entry type as value.

Here is an example. Imagine the process instance is storing the id of an approval request in a process variable called
`varRequestId`. The system responsible for storing approval requests fires data entry events supplying the
data and using the entry type `approvalRequest` and the id of the request as `entryId`. In order to
create a correlation in task `task_approve_request` of the `process_approval_process` we would provide the following configuration
of the correlator:

[source,kotlin]
----
@Bean
open fun processVariablesCorrelator() = ProcessVariablesCorrelator(

  ProcessVariableCorrelation("process_approval_process",
    mapOf(
      "task_approve_request" to mapOf(
        "varRequestId" to "approvalRequest"
      )
    )
  )
)
----
If the process instance now contains the approval request id `"4711"` in the process variable `varRequestId`
and the process reaches the task `task_approve_request`, the task will get the following correlation created
(here written in JSON):

[source,json]
----
"correlations": [
  { "entryType": "approvalRequest", "entryId": "4711" }
]
----


=== Command transmission

In order to control sending of commands to command gateway, the command sender activation property
`camunda.taskpool.sender.enabled` (default is `true`) is available. If disabled, the command sender
will log any command instead of sending it to the command gateway.

The Spring event listeners receiving events from the Camunda Engine plugin are called before the engine commits the transaction.
Since all processing inside collector and enricher is performed synchronous, the sender must waits until transaction to
be successfully committed before sending any commands to the command gateway. Otherwise, on any error
the transaction would be rolled back and the command would create an inconsistency between the taskpool and the engine.

The default provided command sender (type: `tx`) is collects all task commands during one transaction, group them by task id
and accumulates by creating one command reflecting the intent of the task operation. It uses Axon Command Bus (encapsulated
by the `AxonCommandListGateway`.

TIP: If you want to implement a custom command sending, please provide your own implementation of the interface `CommandSender`
(register a Spring Component of the type) and set the property `camunda.taskpool.collector.sender.type` to `custom`.


