package io.holunda.polyflow.client.processengineapi

import io.holunda.polyflow.spring.ApplicationNameBeanPostProcessor
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Import

@SpringBootApplication
@EnableConfigurationProperties(EngineClientProperties::class)
@Import(ApplicationNameBeanPostProcessor::class)
class ProcessEngineApiClientPropertiesTestApplication
