#!/bin/bash

case "$1" in
   "build")
     docker build -t tasklist-angular-build .
     ;;
   "run")
     docker run -it --net=host \
        -v `pwd`/src:/opt/build/src \
        -v `pwd`/src-gen:/opt/build/src-gen \
        tasklist-angular-build \
        npm start
     ;;

   *)
     echo "No command detected. Try $0 build | run"
     ;;
esac


