package io.holunda.camunda.taskpool.collector.properties

import io.holunda.camunda.taskpool.collector.CamundaTaskpoolCollectorProperties
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.context.properties.EnableConfigurationProperties

@SpringBootApplication
@EnableConfigurationProperties(CamundaTaskpoolCollectorProperties::class)
class PropertiesTestApplication
